// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwRohXLoU5NNlFS8NVp2EN08V9buX1y8',
    appId: '1:522780245171:web:9ba39006213db894d844c6',
    messagingSenderId: '522780245171',
    projectId: 'dhomotic',
    authDomain: 'dhomotic.firebaseapp.com',
    databaseURL: 'https://dhomotic-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dhomotic.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvU5h4VkBOHy5OrCH-NSLi338F7js2V_w',
    appId: '1:522780245171:android:5df783000060eca4d844c6',
    messagingSenderId: '522780245171',
    projectId: 'dhomotic',
    databaseURL: 'https://dhomotic-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dhomotic.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnVVRgo6dy4sAgaj3kQYapJs3TxzMUzkE',
    appId: '1:522780245171:ios:a0ba4b872ede644ad844c6',
    messagingSenderId: '522780245171',
    projectId: 'dhomotic',
    databaseURL: 'https://dhomotic-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dhomotic.appspot.com',
    androidClientId: '522780245171-5qu1mmdnkrnfjflo900pfgbht3kmgc2o.apps.googleusercontent.com',
    iosClientId: '522780245171-0fv60562859ed2mnijvsqj6hkfiui1o4.apps.googleusercontent.com',
    iosBundleId: 'com.blecat.dhomeotic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnVVRgo6dy4sAgaj3kQYapJs3TxzMUzkE',
    appId: '1:522780245171:ios:a0ba4b872ede644ad844c6',
    messagingSenderId: '522780245171',
    projectId: 'dhomotic',
    databaseURL: 'https://dhomotic-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'dhomotic.appspot.com',
    androidClientId: '522780245171-5qu1mmdnkrnfjflo900pfgbht3kmgc2o.apps.googleusercontent.com',
    iosClientId: '522780245171-0fv60562859ed2mnijvsqj6hkfiui1o4.apps.googleusercontent.com',
    iosBundleId: 'com.blecat.dhomeotic',
  );
}
